SELECT
    DISTINCT N_NAME,
    COUNT(O_ORDERKEY) 
FROM ORDERS
INNER JOIN CUSTOMER ON
    ORDERS.O_CUSTKEY =  CUSTOMER.C_CUSTKEY
INNER JOIN NATION ON
    NATION.N_NATIONKEY = CUSTOMER.C_NATIONKEY
GROUP BY NATION.N_NAME
ORDER BY 
    COUNT(O_ORDERKEY) DESC;
