SELECT
    DISTINCT N_NAME,
    SUM(L_QUANTITY) 
FROM ORDERS
INNER JOIN LINEITEM ON
    ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY
INNER JOIN CUSTOMER ON
    ORDERS.O_CUSTKEY =  CUSTOMER.C_CUSTKEY
INNER JOIN NATION ON
    NATION.N_NATIONKEY = CUSTOMER.C_NATIONKEY
GROUP BY NATION.N_NAME
ORDER BY 
    SUM(L_QUANTITY)  DESC
LIMIT 10;
