SELECT
    C_NAME,
    O_ORDERKEY,
    O_COMMENT
FROM
    CUSTOMER
LEFT JOIN ORDERS ON
    CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
WHERE 
	INSTR(O_COMMENT, 'special request')>0  
--	OR
--	O_ORDERKEY == NULL
	group by C_NAME
;
